version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '5000:5000'
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - 'RUN=flask run --host=0.0.0.0 --port=5000'
    command: flask run --host=0.0.0.0 --port=5000
