version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - '5000:5000'
    environment:
      - FLASK_APP=rest.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - 'RUN=flask run --host=0.0.0.0 --port=5000'
    command: flask run --host=0.0.0.0 --port=5000

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest    
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=Ritravatra00043)"
    ports:
      - '1433:1433'

    # volumes:
    #   - ./db:/docker-entrypoint-initdb.d/:ro
    #   - dbdata:/var/lib/mysql-files

# volumes:
#   dbdata:
